### ISSUE TITLE
Forge is broken

### ISSUE THREAD

**Issue by valiray** [PrismLauncher/PrismLauncher#2170]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

when trying to use a pack that is using version 43.3.8 of forge you get this [error](https://mclo.gs/wL6h0ou), downgrading back to Forge 43.3.7 makes it work again

### Steps to reproduce

make or use a pack using Forge 43.3.8 for version 1.19.2 

### Suspected cause

looks like it might be something to do with [this issue](https://github.com/PrismLauncher/PrismLauncher/issues/1934)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by DragooKnight** [comment]
Coming in from the other end, just read a recent Forge thread about Mojang removing a domain name and borking the installer, hope that helps here.

**Comment by Trial97** [comment]
Forge mod loader for Minecraft versions 1.13 and later are currently broken in Prism Launcher. Solving this turned out to be more complicated than we initially thought, so please be patient while everything is sorted out.

This is not an issue on Forge's end so please do not report it to them. They updated many of their old installers due to a domain removed by Mojang (which due to an oversight caused them to crash) - which is not something we were prepared for.

**Comment by Trial97** [comment]
Here is a small to do that we need to fix:
- [x] fix metadata (because they regenerated all the installers we need to regenerate all the forge metadata also)
- [x] find a fix for: https://github.com/ZekerZhayard/ForgeWrapper/issues/20

**Comment by Trial97** [comment]
This should be solved now.
If you have problems with the cache just delete `assets` `libraries` and `meta` folders that are inside the prism root data folder. and this will force prism to pick up the new meta and new files.

**Comment by caleb39411** [comment]
I deleted the folders mentioned, and then also my entire prism folder, but I'm still having the same [issue](https://mclo.gs/4obRyA8).

**Comment by Braxbro** [comment]
It is not. Followed all steps (deleted `assets`, `libraries`, `meta`, `cache`, and `metacache`) and no dice.

```
Prism Launcher version: 8.0 (official)


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.213.51, 13.107.246.51]

textures.minecraft.net resolves to:
    [13.107.246.51, 13.107.213.51]

api.mojang.com resolves to:
    [13.107.246.51, 13.107.213.51]


Minecraft folder is:
C:/Users/babro/AppData/Roaming/PrismLauncher/instances/Create- Above and Beyond/.minecraft


Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe


Java is version 1.8.0_333, using 64 (amd64) architecture, from Oracle Corporation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/babro/AppData/Roaming/PrismLauncher/instances/Create- Above and Beyond/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/io/github/zekerzhayard/ForgeWrapper/1.5.8-prism/ForgeWrapper-1.5.8-prism.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forge/1.16.5-36.2.34/forge-1.16.5-36.2.34-launcher.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/babro/AppData/Roaming/PrismLauncher/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Params:
  --username  --version 1.16.5 --gameDir C:/Users/babro/AppData/Roaming/PrismLauncher/instances/Create- Above and Beyond/.minecraft --assetsDir C:/Users/babro/AppData/Roaming/PrismLauncher/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.34 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 7604


Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:170)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 2.
```

**Comment by TheKodeToad** [comment]
Make sure you restart the launcher!

Also, I found only deleting meta is necessary :P

**Comment by TheKodeToad** [comment]
If you need any more support please join the [Discord server](https://discord.gg/ArX2nafFz2)
We are confident this specific issue has been solved.
