### ISSUE TITLE
Network error on Curseforge mod download screen

### ISSUE THREAD

**Issue by FractalGeodes** [PrismLauncher/PrismLauncher#2254]
### Operating System

Windows 11, but bug has been reproduced on other platforms as well.

### Version of Prism Launcher

8.2

### Version of Qt

6.6.2

### Description of bug

When I tried to use the mod downloader to download a mod from Curseforge, the mod list initially loaded the top mods, but after trying to search started erroring and showing the popup "A network error occurred. Could not load mods."
The issue persisted after restarting both Prism and our computer (instead erroring before even the top mods load), and multiple others have reported having this issue as well. Curseforge's frontend works fine.

### Steps to reproduce

* Edit any instance
* Open the add mods screen
* Open the Curseforge tab

### Suspected cause

Possibly a change to Curseforge's API?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Pockett-Dev** [comment]
I am having this same issue. Windows 10 is the only difference I have from you

**Comment by ChiefArug** [comment]
CurseForge is currently having issues as well, this is probably caused by the same thing and so is up to CF to fix.
The [CF discord](https://discord.gg/curseforge) has a Current Issues channel for updates on the issue.

**Comment by Trial97** [comment]
This should be fixed now: https://discord.com/channels/428228256236306434/971826395548381186/1223151045815832687
![image](https://github.com/PrismLauncher/PrismLauncher/assets/42720688/c26f8d33-e33f-43e6-85f6-6bd80755b942)

**Comment by FooterManDev** [comment]
Heya, this is not fixed it seems. I cannot access Curseforge or Modrinth in the app.
![image](https://github.com/PrismLauncher/PrismLauncher/assets/71946346/9feb8dce-809c-4b92-9c48-d1c81d0054d9)
Arch linux
