### ISSUE TITLE
 failed prism launcher running the game 

### ISSUE THREAD

**Issue by fatememehrzad** [PrismLauncher/PrismLauncher#2514]
### Version of Prism Launcher

Instance update failed because: Component metadata update task failed while downloading from remote server: One or more subtasks failed prism launcher

### Version of Qt

8.3

### Description of bug

Instance update failed because: Component metadata update task failed while downloading from remote server: One or more subtasks failed prism launcher

### Steps to reproduce

Instance update failed because: Component metadata update task failed while downloading from remote server: One or more subtasks failed prism launcher

### Suspected cause

Instance update failed because: Component metadata update task failed while downloading from remote server: One or more subtasks failed prism launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
delete the meta folder form inside the root folder.
If still persist full prism logs

**Comment by Trial97** [comment]
And next time do not spam other issues.

**Comment by fatememehrzad** [comment]
what do you mean

**Comment by Trial97** [comment]
delete the folder found at:

fields:
  - name: Portable (Windows / Linux)
    value: '`./meta` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/meta`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
  - name: macOS
    value: '`~/Library/Application Support/PrismLauncher/meta`'
  - name: Linux
    value: '`~/.local/share/PrismLauncher/meta`'
  - name: Flatpak
    value: '`~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/meta`'
---

restart prism and try again

**Comment by fatememehrzad** [comment]
didn't work

**Comment by Trial97** [comment]
fields:
  - name: Portable (Windows / Linux)
    value: '`./logs/PrismLauncher-0.log` In the PrismLauncher folder'
  - name: Windows
    value: '`%APPDATA%/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Scoop
    value: '`%HOMEPATH%\scoop\persist\prismlauncher\logs\PrismLauncher-0.log`'
  - name: macOS
    value: '`~/Library/Application Support/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Linux
    value: '`~/.local/share/PrismLauncher/logs/PrismLauncher-0.log`'
  - name: Flatpak
    value: '`~/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/logs/PrismLauncher-0.log`'
---

Please send logs! The recommended site to upload your logs to is [mclo.gs](https://mclo.gs/).

**Comment by fatememehrzad** [comment]
still didn't work

**Comment by Trial97** [comment]
Closing this as user is unwilling to send logs.

**Comment by fatememehrzad** [comment]
https://api.mclo.gs/1/raw/XYbcv6E

**Comment by fatememehrzad** [comment]
![Uploading Screenshot 2024-06-15 at 15.03.44.png…]()

**Comment by Trial97** [comment]
That is not the file I mentioned .Please upload the file mentioned here:https://github.com/PrismLauncher/PrismLauncher/issues/2514#issuecomment-2168637556

**Comment by jwols123** [comment]
Hello, i have this same problem. I've tried deleting the meta folder, but it didn't work. [Log](https://mclo.gs/gO9sA6P)

**Comment by tarkh** [comment]
Same here.
Forge version.
"Component metadata update task failed while downloading from remote server:"

Tail log:
```
132955.872 D | [launcher.instance.profile.resolve]: "1.20.1 Technoterra (OLD)" | Remote loading is being run for "Forge"
132955.948 W | Checksum mismatch, download is bad.
132956.022 W | Checksum mismatch, download is bad.
132956.102 W | Checksum mismatch, download is bad.
132956.102 D | [launcher.instance.profile.resolve]: Remote task 0 failed:  "One or more subtasks failed"
132956.102 D | [launcher.instance.profile]: "1.20.1 Technoterra (OLD)" | Component list update/resolve task failed  Reason: "Component metadata update task failed while downloading from remote server:\nOne or more subtasks failed"
132956.123 D | "1.20.1 Technoterra (OLD)" | Component list save performed now
132956.123 D | [launcher.instance.profile.resolve]: Loading components
132956.123 D | "1.20.1 Technoterra (OLD)" | Component list save is scheduled
132956.123 D | [launcher.instance.profile.resolve]: "1.20.1 Technoterra (OLD)" | Remote loading is being run for "Forge"
132956.142 D | [launcher.instance.profile]: "1.20.1 Technoterra (OLD)" | Applying "org.lwjgl3" GOOD
132956.143 D | [launcher.instance.profile]: "1.20.1 Technoterra (OLD)" | Applying "net.minecraft" GOOD
132956.143 D | [launcher.instance.profile]: "1.20.1 Technoterra (OLD)" | Applying "net.minecraftforge" GOOD
132956.179 W | QLayout: Attempting to add QLayout "" to InstanceWindow "", which already has a layout
132956.193 W | "One or more subtasks failed"
132956.356 W | Checksum mismatch, download is bad.
132956.448 W | Checksum mismatch, download is bad.
132956.527 W | Checksum mismatch, download is bad.
132956.527 D | [launcher.instance.profile.resolve]: Remote task 0 failed:  "One or more subtasks failed"
132956.527 D | [launcher.instance.profile]: "1.20.1 Technoterra (OLD)" | Component list update/resolve task failed  Reason: "Component metadata update task failed while downloading from remote server:\nOne or more subtasks failed"
132956.527 W | "One or more subtasks failed"
132961.374 D | "1.20.1 Technoterra (OLD)" | Component list save performed now
```

**Comment by tarkh** [comment]
Same here, fixed on Arch Linux by reinstalling app (sudo pacman -S prismlauncher)

**Comment by minerCodeMaster** [comment]
Deleted meta folder on Windows, prism 9.1. Fixed the issue 👌

**Comment by Grandev-0** [comment]
> Deleted meta folder on Windows, prism 9.1. Fixed the issue 👌

Same

**Comment by chililisoup** [comment]
Deleted meta folder on Arch Linux (flatpak), prism 9.1. Fixed the issue 👌

**Comment by whitehenry18** [comment]
Changing my forge version (not the minecraft version) worked for me on windows 11, prism 9.1

**Comment by mothmakes** [comment]
Fixed this on NixOS (linux) by changing the forge version. Thanks @whitehenry18 ! Deleting meta folder had no effect.

Edit > Version > (whichever forge you have) > change version. I selected the most recent version, YMMV.

EDIT: I suspect the issue lies with Prism not being able to identify the forge version to download in some way. Selecting it manually forces it to download.

**Comment by adrien-delhom** [comment]
Prism 9.2, same issue on Windows. I deleted the meta folder but I still have the issue. The issue appears after upgrade my ATM10 modpack, this is [my log file](https://mclo.gs/9SjV6ap)

EDIT: it's look like to be about neoforged

![Image](https://github.com/user-attachments/assets/a59ee397-7b2a-43ba-842b-f0d943cc868b)

**Comment by femininefreyanyctophile** [comment]
Updating Prism launcher worked for me

**Comment by MonkeysWithPie** [comment]
> it's look like to be about neoforged

can confirm, i experienced this as well and after deleting just the `net.neoforged` meta folder it worked fine

**Comment by tpkowastaken** [comment]
For me removing the folder AND restarting prism launcher worked.

**Comment by raitoguu** [comment]
reselect **Forge** loader via `Version > Install Loader > Forge > 11.15.1.2318`
this forces prism to download forge bc it couldnt find the metadata i assume

**Comment by ryoko7** [comment]
deleting index.json under net.neoforged worked for me
Before that, the name had weird random numbers in it
So it may just be that the metadata couldn't be found because something changed the name

**Comment by QazCetelic** [comment]
I also had this issue but restarting the launcher after deleting the `meta` folder fixed it for me.

**Comment by Dfg-22** [comment]
Experiencing the same issue, but nothing anyone has suggested so far has helped, and I can't launch any instance, create a new instance or even launch the game on a different launcher. Logs: https://pastebin.com/xzkxnrRS password: U2GWj3qwYp

<img width="440" height="130" alt="Image" src="https://github.com/user-attachments/assets/1e802575-f4a7-4b7a-b2f8-8ff44dbdcdba" />

<img width="720" height="474" alt="Image" src="https://github.com/user-attachments/assets/4fe8dd21-7e65-4e5f-a30f-8694426db067" />

**Comment by LeshaTheBeginner** [comment]
**Log pinned at the bottom**

I have the same issue! The issue persists with forge (enabled or disabled). I have to remove forge to get Minecraft going, and adding it back shows an error first (image below),

<img width="1444" height="790" alt="Image" src="https://github.com/user-attachments/assets/efc7ad03-9a53-48c0-b4ce-6282b6ff281a" />

And after i add it, it doesn't recognize itself,

<img width="1460" height="806" alt="Image" src="https://github.com/user-attachments/assets/6acf25d3-3e20-44c6-b214-a96154b78a90" />
and the error shows up.

<img width="1460" height="806" alt="Image" src="https://github.com/user-attachments/assets/d43e2f8a-a35e-4f42-b63e-3aa3c000953f" />

Deleting the metadata doesn't help, as even after removing the folder, the error persists. Here's the folder (nothing inside the forge folder)
<img width="1012" height="672" alt="Image" src="https://github.com/user-attachments/assets/c686404b-2b98-4071-89f7-83fbc5fd50f3" />

NOW THIS TURNS A WEIRD TURN, BECAUSE ALL THIS ISN'T AN ISSUE IN OFFLINE MODE!



Here's the log
[PrismLauncher-0.log](https://github.com/user-attachments/files/23915110/PrismLauncher-0.log)

**Comment by Dfg-22** [comment]
Update: I partially fixed the issue (partially meaning on some instances) by reinstalling Java completely and then using specifically Java 21.

**Comment by Mace68** [comment]
Simply restarting Prism (9.4 on Linux) is all it took for me to fix it. Plus it seemed to only be an issue with Forge instances.
