### ISSUE TITLE
Crash when resizing window ONLY when zink enabled

### ISSUE THREAD

**Issue by barraIhsan** [PrismLauncher/PrismLauncher#3366]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.2

### Version of Qt

Qt 6.8.1

### Description of bug

When using zink, resizing a window (either in the main menu, or in a world) will cause a crash and **sometimes** the logs produced
```
MESA: error: zink: DEVICE LOST!
MESA: error: zink: DEVICE LOST!
MESA: error: zink: DEVICE LOST!
MESA: error: zink: DEVICE LOST!
```
(no crash, had to manuallty `Kill`) and also **sometimes** the logs shows the java crash
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000799a460c73d3, pid=355546, tid=355708
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.6+7 (21.0.6+7) (build 21.0.6+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (21.0.6+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnvidia-glcore.so.565.77+0xac73d3]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/barra/.local/share/PrismLauncher/instances/Fabulously Optimized/minecraft/core.355546)
#
# An error report file with more information is saved as:
# /home/barra/.local/share/PrismLauncher/instances/Fabulously Optimized/minecraft/hs_err_pid355546.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
```
and crashed with exitcode `6`. But sometimes it also doesn't show anything on the log

Tested with temurin (`jdk21-temurin` on AUR) and also with OpenJDK (`jre21-openjdk` on Arch). This doesn't occur when zink turned off.

In this case, the logs said nothing and crashed.
![Image](https://github.com/user-attachments/assets/cd7cf88f-f56b-41f7-96c7-b9cc8a3f59e5)

And I also got a java crash
![Image](https://github.com/user-attachments/assets/43cce9d4-1494-48d4-91b6-9cf30b64aa9b)

### Steps to reproduce

Launch minecraft with zink enabled (Settings > Minecraft > Tweaks > Performance > Use Zink), and then resize the window, sometimes it takes multiple times to see the crash

### Suspected cause

It's obviously a zink fault, but I'm not really sure. Should I also (or maybe only?) make an issue on the Zink project.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This issue doesn't appear to be related to PrismLauncher itself. For questions or problems not directly tied to the launcher, we recommend joining our [Discord server](https://prismlauncher.org/discord) where the community can provide assistance.

**Comment by ChickenIQ** [comment]
Add "__GL_THREADED_OPTIMIZATIONS=0" to your environment variables, it should fix it.

**Comment by barraIhsan** [comment]
> Add "__GL_THREADED_OPTIMIZATIONS=0" to your environment variables, it should fix it.

The crash still occurs
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007643832d3783, pid=13482, tid=13590
#
# JRE version: OpenJDK Runtime Environment Temurin-21.0.6+7 (21.0.6+7) (build 21.0.6+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Temurin-21.0.6+7 (21.0.6+7-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnvidia-glcore.so.570.86.16+0xad3783]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/barra/.local/share/PrismLauncher/instances/1.21.4/minecraft/core.13482)
#
# An error report file with more information is saved as:
# /home/barra/.local/share/PrismLauncher/instances/1.21.4/minecraft/hs_err_pid13482.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Process crashed with exitcode 6.
```
I even tried with new instances of Vanilla 1.21.4

**Comment by ChickenIQ** [comment]
Did you set it for the instance or system wide?
If you set it system wide, you will have to log out and log back in.

**Comment by barraIhsan** [comment]
> Did you set it for the instance or system wide? If you set it system wide, you will have to log out and log back in.

instance wide in the Settings > Env variables

**Comment by kyylvisa** [comment]
For the sake of any future users, I too saw the same issue though in my case the system would hard lock upon resizing the game window.

    __GL_THREADED_OPTIMIZATIONS=0

Did prevent the crash/issue in the menus but once in game it no longer helped. Definitely a zink issue.
