### ISSUE TITLE
PrismLauncher x86_64-AppImage 9.2 subtasks fail with "TLS initialization failed" errors

### ISSUE THREAD

**Issue by ewe2** [PrismLauncher/PrismLauncher#3422]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.2 x86_64

### Version of Qt

Qt 6.4.2 on system but this is an AppImage so it would be an issue with TLS library bundled within.

### Description of bug

We expect instances to run. Attempting to run an instance will start a dialogue window "please wait..." Working... Initiallziing.  This never completes. Running this version of PrismLauncher from the command-line reveals that there is a recurring error with many subtasks, for example:

80.690 C | [launcher.task.net.download]: "{bc5df658-c471-4b72-a615-cc4c53609ff9}" Failed "https://meta.prismlauncher.org/v1/index.json" with reason QNetworkReply::UnknownNetworkError
    80.690 C | [launcher.task.net.download]: "{bc5df658-c471-4b72-a615-cc4c53609ff9}" HTTP Status 0 ;error "TLS initialization failed"
    80.690 C | [launcher.task.net.download]: "{ecd85f3c-ec8c-439a-b31c-d4677e57a34b}" Failed "https://meta.prismlauncher.org/v1/index.json" with reason QNetworkReply::UnknownNetworkError
    80.690 C | [launcher.task.net.download]: "{ecd85f3c-ec8c-439a-b31c-d4677e57a34b}" HTTP Status 0 ;error "TLS initialization failed"
    80.690 C | [launcher.task.net.download]: "{8ca555ae-d4e1-41d8-9528-1764f0d65f1d}" Failed "https://meta.prismlauncher.org/v1/index.json" with reason QNetworkReply::UnknownNetworkError
    80.690 C | [launcher.task.net.download]: "{8ca555ae-d4e1-41d8-9528-1764f0d65f1d}" HTTP Status 0 ;error "TLS initialization failed"

### Steps to reproduce

Attempt any subtask like add an instance or run one. A message box will appear, stating Working... initializing. It never completes. Rolling back to 9.1 restores normal operation so the issue is with the libraries in the AppImage for 9.2

### Suspected cause

As noted above, it seems there is an incompatibility with the Qt SSL/TLS libraries in Prism 9.2. for the linux AppImage.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Trial97** [comment]
This is because we bumped the qt version without also incrementing the OpenSSL version that is copied in the app image it should be fixed(it is even planned for the next release) so try nightly https://nightly.link/PrismLauncher/PrismLauncher/workflows/trigger_builds/develop

**Comment by ewe2** [comment]
So far the 10-develop nightly is still failing the TLS, tried the 50ab1b2, i get errors about the backend key and then the same errors as above.

**Comment by MrDoritos** [comment]
I was also having the same issue when I updated to the latest release 9.2

`     0.002 W | [qt.tlsbackend.ossl]: Incompatible version of OpenSSL (built with OpenSSL >= 3.x, runtime version is < 3.x)`

I went ahead and compiled the latest openssl when this happened. Whatever my system (Ubuntu 24.04 LTS) uses as the default `/lib/x86_64-linux-gnu/libssl.so.3`  just wasn't working.

Since compiling openssl doesn't overwrite the libraries in `/lib/x86_64-linux-gnu` and uses `/usr/local/ssl/lib64` instead, I just set the `LD_LIBRARY_PATH` variable and it the network functions in the program work as intended.

`LD_LIBRARY_PATH=/usr/local/ssl/lib64 ./PrismLauncher-Linux-x86_64.AppImage`

I tried the nightly just like @ewe2 did and encountered the same issue. Doing what I did fixed both the release and nightly.

**Comment by raxod502** [comment]
`/lib/x86_64-linux-gnu/libssl.so.3` works fine for me, however I have to explicitly export `LD_LIBRARY_PATH=/lib/x86_64-linux-gnu` before running the AppImage, when this should be working out of the box (especially as it's an AppImage).

**Comment by Trial97** [comment]
We are aware that the appimage is broken for 9.2.
Some stuff was broken on linuxdeploy side for now, so the last 9.2 action that has a working appimage is https://nightly.link/PrismLauncher/PrismLauncher/actions/runs/13270653107 .
So in case until next release the linuxdeploy is not fixed please try to use the mentioned link.

**Comment by ewe2** [comment]
> `/lib/x86_64-linux-gnu/libssl.so.3` works fine for me, however I have to explicitly export `LD_LIBRARY_PATH=/lib/x86_64-linux-gnu` before running the AppImage, when this should be working out of the box (especially as it's an AppImage).

This doesn't work for me, either because my base qt6 libraries don't have the version information or they're not up to version 6.5, the latest nightly does not work for me either. I am running a conservative MX distribution so it's not bleeding-edge stuff.

**Comment by ewe2** [comment]
I have tried the latest artifact from the new builds and the Qt6 is working but the ssl is still not. It seems whatever I do, the libraries are seeking out the wrong ssl libraries, ignoring the ssl3 libraries right next to them  and I cannot remove these outdated libraries without removing major system components that for some reason still depend on outdated ssl code.  So I had to follow @MrDoritos method and compile my own ssl3 libraries and point the launcher towards that and it works.  Perhaps this will have to do unless we can figure out a fail-safe method of ssl library detection.

**Comment by MrDoritos** [comment]
Following up on that,

I just tried:

`./Configure --prefix=/usr/local --openssldir=/usr/local/ssl '-Wl,--enable-new-dtags' '-Wl,-rpath,$(LIBRPATH)'`

as opposed to `--prefix=/usr/local/ssl` from my original reply

To see if it was searching the wrong directories because this will install onto `/usr/local/lib64` instead of `/usr/local/ssl/lib64`, I didn't try it immediately because I wouldn't know if my install would like an OpenSSL version change. It still doesn't make the launcher recognize it, and my system seems fine lol. 

I still have to set `LD_LIBRARY_PATH=/usr/local/lib64`. I'm guessing the launcher or the AppImage searches `/usr/local/lib` instead by default, but I'm not sure. I was unable to configure OpenSSL to install to `/usr/local/lib` instead of `/usr/local/lib64`, but I honestly didn't try hard enough. 

Placing `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64` in your `~/.bashrc` is not that bad of a workaround really.

**Comment by raxod502** [comment]
You can also use a wrapper script or modify the desktop launcher; I personally manage all software on my system using APT, and put together a small imitation of `makepkg` from Arch Linux, which lets me take arbitrary third-party software and build it into `.deb` files, and handle regular updates. The packaging steps for Prism Launcher look like this:

```bash
package() {
    chmod +x "${src}/prismlauncher.AppImage"
    (
        cd "${tmp}"
        "${src}/prismlauncher.AppImage" --appimage-extract
    )

    mkdir -p "${pkg}/usr/bin"
    ln "${src}/prismlauncher.AppImage" "${pkg}/usr/bin/prismlauncher"

    mkdir -p "${pkg}/usr/share/applications"
    cp "${tmp}/squashfs-root/org.prismlauncher.PrismLauncher.desktop" \
       "${pkg}/usr/share/applications/prismlauncher.desktop"
    sed -Ei 's|^Icon=.*|Icon=prismlauncher|' "${pkg}/usr/share/applications/prismlauncher.desktop"

    # https://github.com/PrismLauncher/PrismLauncher/issues/3422
    sed -Ei 's|^Exec=|Exec=env LD_LIBRARY_PATH=/lib/x86_64-linux-gnu |' "${pkg}/usr/share/applications/prismlauncher.desktop"

    mkdir -p "${pkg}/usr/share/icons/hicolor/scalable/apps"
    ln "${tmp}/squashfs-root/usr/share/icons/hicolor/scalable/apps/org.prismlauncher.PrismLauncher.svg" \
       "${pkg}/usr/share/icons/hicolor/scalable/apps/prismlauncher.svg"
}
```

So you can see here I am simply adding an environment variable setting for `LD_LIBRARY_PATH` to the `prismlauncher.desktop` entry, after extracting that file from the AppImage. You could also do the same thing in your user-local `.desktop` folder, to avoid the need to do anything as root.

**Comment by Octol1ttle** [comment]
Does this issue still happen on 10.0.5 or 11?

**Comment by ewe2** [comment]
Appimage 10.0.5 works fine, I haven't tried 11. Nice trick with the apt code raxod.
