### ISSUE TITLE
Export options do not save when closing the export dialog box.

### ISSUE THREAD

**Issue by NetUserGet** [PrismLauncher/PrismLauncher#3552]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 9.2

### Version of Qt

Qt 6.8.2

### Description of bug

When exporting a modpack and you un-toggle a file and export it doesn't save the un-toggled file when you reopen the export dialog option.

### Steps to reproduce

* Export a modpack as a mrpack or curseforge zip
* Untoggle a file (servers.dat, options.txt, etc) and export
* Reopen the export dialog
* Notice that the untoggled file is back to its default option. 

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TheKodeToad** [comment]
Already fixed in next version!

**Comment by Llohgun** [comment]
> Already fixed in next version!

Assuming the "not planned" was selected as it was already considered updated, this is still an issue in 9.4

**Comment by NetUserGet** [comment]
Yes, this is still an issue. Even with the latest release, 9.4.

**Comment by TheKodeToad** [comment]
The next major version - not the current version!

**Comment by NetUserGet** [comment]
I just compiled the develop branch and the file overrides save! I would mark this as completed when 10.0 comes out.
