### ISSUE TITLE
9.3+ Regression; Segfault on X11 OpenBox LXDE

### ISSUE THREAD

**Issue by theofficialgman** [PrismLauncher/PrismLauncher#4130]
### Operating System

Other, Linux

### Version of Prism Launcher

9.3 and newer

### Version of Qt

5.15.2

### Description of bug

segfaults on launch

note: the GLIB errors present in the below log do NOT occur on 9.2 and earlier and neither does the segfault. The segfault also does not occur when using wayland labwc on 9.3+.
```
Launcher Dir: /usr/share/PrismLauncher
No missing dependencies found.
chmod: changing permissions of '/usr/share/PrismLauncher/bin/prismlauncher': Operation not permitted
     0.000 D | Testing "/home/gman/.local/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Testing "/usr/share/PrismLauncher/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Loading logging rules from: "/usr/share/PrismLauncher/share/PrismLauncher/qtlogging.ini"
     0.000 D | Setting log rules:
     0.000 D |      "*.debug=true"
     0.000 D |      "launcher.auth.credentials.debug=false"
     0.000 D |      "launcher.task=false"
     0.000 D |      "launcher.task.net=true"
     0.000 D |      "launcher.task.net.download.debug=false"
     0.000 D |      "launcher.task.net.metacache=false"
     0.000 D |      "launcher.task.net.metacache.http=true"
     0.000 D |      "launcher.task.net.upload=true"
     0.000 D |      "qt.*.debug=false"
     0.000 D | <> Log initialized.
     0.000 D | <> No migration needed from "PolyMC"
     0.000 D | <> No migration needed from "MultiMC"
     0.000 D | Prism Launcher, © 2022-2025 Prism Launcher Contributors, © 2021-2022 PolyMC Contributors, © 2012-2021 MultiMC Contributors
     0.000 D | Version                    :  "9.3"
     0.000 D | Platform                   :  "debian"
     0.000 D | Git commit                 :  ""
     0.000 D | Git refspec                :  "refs/heads/stable"
     0.000 D | Compiled for               :  "Linux 6.14.0-1011-oracle aarch64"
     0.000 D | Compiled by                :  "Clang - 10.0.0"
     0.000 D | Build Artifact             :  ""
     0.000 D | Updates Enabled           :  No
     0.000 D | Work dir before adjustment :  "/home/gman"
     0.000 D | Work dir after adjustment  :  "/home/gman/.local/share/PrismLauncher"
     0.000 D | Adjusted by                :  "Persistent data path"
     0.000 D | Binary path                :  "/usr/share/PrismLauncher/bin"
     0.000 D | Application root path      :  "/usr/share/PrismLauncher"
     0.000 D | <> Paths set.
     0.012 D | Detected default console font: "Liberation Mono" , substitutions: ""
     0.042 D | <> Settings loaded.
     0.056 D | Detecting proxy settings...
     0.056 D | Using no proxy is an option!
     0.056 D | <> Network done.
     0.058 D | Your language is "en_US"
     0.058 D | <> Translations loaded.
     0.059 D | Started watching  "/home/gman/.local/share/PrismLauncher/icons"
     0.059 D | Sorting icon list...
     0.059 D | <> Instance icons initialized.
     0.059 D | [Theme] Determining System Widget Theme...
     0.059 D | [Theme] System theme seems to be: "fusion"
     0.059 D | [Theme] <> Initializing Icon Themes
     0.059 D | [Theme] Loaded Built-In Icon Theme "pe_colored"
     0.060 D | [Theme] Loaded Built-In Icon Theme "pe_light"
     0.060 D | [Theme] Loaded Built-In Icon Theme "pe_dark"
     0.060 D | [Theme] Loaded Built-In Icon Theme "pe_blue"
     0.060 D | [Theme] Loaded Built-In Icon Theme "breeze_light"
     0.060 D | [Theme] Loaded Built-In Icon Theme "breeze_dark"
     0.060 D | [Theme] Loaded Built-In Icon Theme "OSX"
     0.060 D | [Theme] Loaded Built-In Icon Theme "iOS"
     0.060 D | [Theme] Loaded Built-In Icon Theme "flat"
     0.060 D | [Theme] Loaded Built-In Icon Theme "flat_white"
     0.060 D | [Theme] Loaded Built-In Icon Theme "multimc"
     0.060 D | [Theme] Icon Theme Folder Path:  "/home/gman/.local/share/PrismLauncher/iconthemes"
     0.060 D | [Theme] <> Icon themes initialized.
     0.060 D | [Theme] <> Initializing Widget Themes
     0.060 D | [Theme] Loading Built-in Theme: "system"
     0.060 D | [Theme] Loading Built-in Theme: "dark"
     0.060 D | [Theme] Loading Built-in Theme: "bright"
     0.060 D | [Theme] <> Initializing System Widget Themes

(prismlauncher:15416): GLib-GObject-WARNING **: 20:48:39.622: cannot register existing type 'GdkDisplayManager'

(prismlauncher:15416): GLib-CRITICAL **: 20:48:39.622: g_once_init_leave: assertion 'result != 0' failed

(prismlauncher:15416): GLib-GObject-CRITICAL **: 20:48:39.622: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(prismlauncher:15416): GLib-GObject-WARNING **: 20:48:39.622: invalid (NULL) pointer instance

(prismlauncher:15416): GLib-GObject-CRITICAL **: 20:48:39.622: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(prismlauncher:15416): GLib-GObject-WARNING **: 20:48:39.622: invalid (NULL) pointer instance

(prismlauncher:15416): GLib-GObject-CRITICAL **: 20:48:39.622: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(prismlauncher:15416): GLib-GObject-WARNING **: 20:48:39.623: cannot register existing type 'GdkDisplay'

(prismlauncher:15416): GLib-CRITICAL **: 20:48:39.623: g_once_init_leave: assertion 'result != 0' failed

(prismlauncher:15416): GLib-GObject-CRITICAL **: 20:48:39.623: g_type_register_static: assertion 'parent_type > 0' failed

(prismlauncher:15416): GLib-CRITICAL **: 20:48:39.623: g_once_init_leave: assertion 'result != 0' failed

(prismlauncher:15416): GLib-GObject-CRITICAL **: 20:48:39.623: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault
```

### Steps to reproduce

launch prismlauncher

### Suspected cause

some change in 9.3

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TimDev9492** [comment]
Can confirm the same bug on Artix Linux, using hyprland as the window manager. I installed prismlauncher using pacman and this is my output on first launch:
```
$ prismlauncher
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
     0.000 D | Testing "/home/tim/.local/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Testing "/usr/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Loading logging rules from: "/usr/share/PrismLauncher/qtlogging.ini"
     0.000 D | Setting log rules:
     0.000 D |      "*.debug=true"
     0.000 D |      "launcher.auth.credentials.debug=false"
     0.001 D |      "launcher.task=false"
     0.001 D |      "launcher.task.net=true"
     0.001 D |      "launcher.task.net.download.debug=false"
     0.001 D |      "launcher.task.net.metacache=false"
     0.001 D |      "launcher.task.net.metacache.http=true"
     0.001 D |      "launcher.task.net.upload=true"
     0.001 D |      "qt.*.debug=false"
     0.001 D | <> Log initialized.
     0.001 D | <> No migration needed from "PolyMC"
     0.001 D | <> No migration needed from "MultiMC"
     0.001 D | Prism Launcher, © 2022-2025 Prism Launcher Contributors, © 2021-2022 PolyMC Contributors, © 2012-2021 MultiMC Contributors
     0.001 D | Version                    :  "9.4"
     0.001 D | Platform                   :  "archlinux"
     0.001 D | Git commit                 :  ""
     0.001 D | Git refspec                :  "refs/heads/stable"
     0.001 D | Compiled for               :  "Linux 6.12.16-1-lts x86_64"
     0.001 D | Compiled by                :  "GNU - 15.2.1"
     0.001 D | Build Artifact             :  ""
     0.001 D | Updates Enabled           :  No
     0.001 D | Work dir before adjustment :  "/home/tim"
     0.001 D | Work dir after adjustment  :  "/home/tim/.local/share/PrismLauncher"
     0.001 D | Adjusted by                :  "Persistent data path"
     0.001 D | Binary path                :  "/usr/bin"
     0.001 D | Application root path      :  "/usr"
     0.001 D | <> Paths set.
     0.057 D | Detected default console font: "Noto Sans Mono" , substitutions: ""
     0.064 D | <> Settings loaded.
     0.064 D | Detecting proxy settings...
     0.064 D | Using no proxy is an option!
     0.064 D | <> Network done.
     0.064 C | Exception: "Unable to open /home/tim/.local/share/PrismLauncher/translations/index_v2.json for reading: No such file or directory"
     0.064 C | Translations Download Failed: index file not readable
     0.064 W | Selected invalid language "" , defaulting to "en_US"
     0.064 D | Your language is ""
     0.064 D | <> Translations loaded.
     0.065 D | Started watching  "/home/tim/.local/share/PrismLauncher/icons"
     0.065 D | Sorting icon list...
     0.065 D | <> Instance icons initialized.
     0.066 D | [Theme] Determining System Widget Theme...
     0.066 D | [Theme] System theme seems to be: "fusion"
     0.066 D | [Theme] <> Initializing Icon Themes
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_colored"
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_light"
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_dark"
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_blue"
     0.066 D | [Theme] Loaded Built-In Icon Theme "breeze_light"
     0.066 D | [Theme] Loaded Built-In Icon Theme "breeze_dark"
     0.066 D | [Theme] Loaded Built-In Icon Theme "OSX"
     0.066 D | [Theme] Loaded Built-In Icon Theme "iOS"
     0.066 D | [Theme] Loaded Built-In Icon Theme "flat"
     0.066 D | [Theme] Loaded Built-In Icon Theme "flat_white"
     0.066 D | [Theme] Loaded Built-In Icon Theme "multimc"
     0.066 D | [Theme] Icon Theme Folder Path:  "/home/tim/.local/share/PrismLauncher/iconthemes"
     0.066 D | [Theme] <> Icon themes initialized.
     0.066 D | [Theme] <> Initializing Widget Themes
     0.066 D | [Theme] Loading Built-in Theme: "system"
     0.066 D | [Theme] Loading Built-in Theme: "dark"
     0.066 D | [Theme] Loading Built-in Theme: "bright"
     0.066 D | [Theme] <> Initializing System Widget Themes
Segmentation fault         prismlauncher$ prismlauncher
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
     0.000 D | Testing "/home/tim/.local/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Testing "/usr/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Loading logging rules from: "/usr/share/PrismLauncher/qtlogging.ini"
     0.000 D | Setting log rules:
     0.000 D |      "*.debug=true"
     0.000 D |      "launcher.auth.credentials.debug=false"
     0.001 D |      "launcher.task=false"
     0.001 D |      "launcher.task.net=true"
     0.001 D |      "launcher.task.net.download.debug=false"
     0.001 D |      "launcher.task.net.metacache=false"
     0.001 D |      "launcher.task.net.metacache.http=true"
     0.001 D |      "launcher.task.net.upload=true"
     0.001 D |      "qt.*.debug=false"
     0.001 D | <> Log initialized.
     0.001 D | <> No migration needed from "PolyMC"
     0.001 D | <> No migration needed from "MultiMC"
     0.001 D | Prism Launcher, © 2022-2025 Prism Launcher Contributors, © 2021-2022 PolyMC Contributors, © 2012-2021 MultiMC Contributors
     0.001 D | Version                    :  "9.4"
     0.001 D | Platform                   :  "archlinux"
     0.001 D | Git commit                 :  ""
     0.001 D | Git refspec                :  "refs/heads/stable"
     0.001 D | Compiled for               :  "Linux 6.12.16-1-lts x86_64"
     0.001 D | Compiled by                :  "GNU - 15.2.1"
     0.001 D | Build Artifact             :  ""
     0.001 D | Updates Enabled           :  No
     0.001 D | Work dir before adjustment :  "/home/tim"
     0.001 D | Work dir after adjustment  :  "/home/tim/.local/share/PrismLauncher"
     0.001 D | Adjusted by                :  "Persistent data path"
     0.001 D | Binary path                :  "/usr/bin"
     0.001 D | Application root path      :  "/usr"
     0.001 D | <> Paths set.
     0.057 D | Detected default console font: "Noto Sans Mono" , substitutions: ""
     0.064 D | <> Settings loaded.
     0.064 D | Detecting proxy settings...
     0.064 D | Using no proxy is an option!
     0.064 D | <> Network done.
     0.064 C | Exception: "Unable to open /home/tim/.local/share/PrismLauncher/translations/index_v2.json for reading: No such file or directory"
     0.064 C | Translations Download Failed: index file not readable
     0.064 W | Selected invalid language "" , defaulting to "en_US"
     0.064 D | Your language is ""
     0.064 D | <> Translations loaded.
     0.065 D | Started watching  "/home/tim/.local/share/PrismLauncher/icons"
     0.065 D | Sorting icon list...
     0.065 D | <> Instance icons initialized.
     0.066 D | [Theme] Determining System Widget Theme...
     0.066 D | [Theme] System theme seems to be: "fusion"
     0.066 D | [Theme] <> Initializing Icon Themes
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_colored"
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_light"
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_dark"
     0.066 D | [Theme] Loaded Built-In Icon Theme "pe_blue"
     0.066 D | [Theme] Loaded Built-In Icon Theme "breeze_light"
     0.066 D | [Theme] Loaded Built-In Icon Theme "breeze_dark"
     0.066 D | [Theme] Loaded Built-In Icon Theme "OSX"
     0.066 D | [Theme] Loaded Built-In Icon Theme "iOS"
     0.066 D | [Theme] Loaded Built-In Icon Theme "flat"
     0.066 D | [Theme] Loaded Built-In Icon Theme "flat_white"
     0.066 D | [Theme] Loaded Built-In Icon Theme "multimc"
     0.066 D | [Theme] Icon Theme Folder Path:  "/home/tim/.local/share/PrismLauncher/iconthemes"
     0.066 D | [Theme] <> Icon themes initialized.
     0.066 D | [Theme] <> Initializing Widget Themes
     0.066 D | [Theme] Loading Built-in Theme: "system"
     0.066 D | [Theme] Loading Built-in Theme: "dark"
     0.066 D | [Theme] Loading Built-in Theme: "bright"
     0.066 D | [Theme] <> Initializing System Widget Themes
Segmentation fault         prismlauncher
```
I have the following environment variables set:
```
XDG_BACKEND=wayland
QT_QPA_PLATFORM=wayland
```

I also tried installing multimc to see if it is a prismlauncher specific issue and multimc launches fine. Seems to be related to prismlauncher specifically...

**Comment by theofficialgman** [comment]
CC @Trial97 @TheKodeToad @getchoo I imagine this has something to do with https://github.com/PrismLauncher/PrismLauncher/pull/3539 or https://github.com/PrismLauncher/PrismLauncher/pull/3585 given the segfault timing with system themes.

**Comment by TheKodeToad** [comment]
I believe this was fixed in 10.0.0: https://github.com/PrismLauncher/PrismLauncher/pull/3690

**Comment by theofficialgman** [comment]
> I believe this was fixed in 10.0.0: [#3690](https://github.com/PrismLauncher/PrismLauncher/pull/3690)

@TheKodeToad just applied that patch to latest stable release, doesn't fix the issue

**Comment by TheKodeToad** [comment]
The one place in both those PRs where a pointer is dereferenced had a null check added.

**Comment by TheKodeToad** [comment]
Try testing on the latest [10.0.0 build](https://nightly.link/PrismLauncher/PrismLauncher/workflows/build/develop) to be sure

**Comment by TimDev9492** [comment]
This is what I get when launching the 10.0.0 dev build:
```sh
$ ./PrismLauncher-Linux-fcd3852-Debug-x86_64.AppImage 
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
```
When I launch it with `QT_QPA_PLATFORM= ./PrismLauncher-...` it launches fine, but uses xorg as the backend. So, it doesn't really solve the issue of running PrismLauncher on wayland... Do you know if I can maybe build the project from source with wayland support?

**Comment by leonpano2006** [comment]
I have same issue on Ubuntu-desktop(gnome)
On Dgx spark (Ubuntu 24.04 with Nvidia-drivers-590-open)

**Comment by Ratstail91** [comment]
I appear to have the same issue on my raspberry pi, using the version installed via pi-apps:

```
kruse@raspberrypi:~ $ prismlauncher
Launcher Dir: /usr/share/PrismLauncher
No missing dependencies found.
chmod: changing permissions of '/usr/share/PrismLauncher/bin/prismlauncher': Operation not permitted
     0.000 D | Testing "/home/kruse/.local/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Testing "/usr/share/PrismLauncher/share/PrismLauncher/qtlogging.ini" ...
     0.000 D | Loading logging rules from: "/usr/share/PrismLauncher/share/PrismLauncher/qtlogging.ini"
     0.000 D | Setting log rules:
     0.000 D |      "*.debug=true"
     0.000 D |      "launcher.auth.credentials.debug=false"
     0.000 D |      "launcher.task=false"
     0.000 D |      "launcher.task.net=true"
     0.000 D |      "launcher.task.net.download.debug=false"
     0.000 D |      "launcher.task.net.metacache=false"
     0.000 D |      "launcher.task.net.metacache.http=true"
     0.000 D |      "launcher.task.net.upload=true"
     0.000 D |      "qt.*.debug=false"
     0.000 D | <> Log initialized.
     0.000 D | <> No migration needed from "PolyMC"
     0.000 D | <> No migration needed from "MultiMC"
     0.000 D | Prism Launcher, © 2022-2025 Prism Launcher Contributors, © 2021-2022 PolyMC Contributors, © 2012-2021 MultiMC Contributors
     0.000 D | Version                    :  "9.4"
     0.000 D | Platform                   :  "debian"
     0.000 D | Git commit                 :  ""
     0.000 D | Git refspec                :  "refs/heads/stable"
     0.000 D | Compiled for               :  "Linux 6.14.0-1013-oracle aarch64"
     0.000 D | Compiled by                :  "Clang - 10.0.0"
     0.000 D | Build Artifact             :  ""
     0.000 D | Updates Enabled           :  No
     0.000 D | Work dir before adjustment :  "/home/kruse"
     0.000 D | Work dir after adjustment  :  "/home/kruse/.local/share/PrismLauncher"
     0.000 D | Adjusted by                :  "Persistent data path"
     0.000 D | Binary path                :  "/usr/share/PrismLauncher/bin"
     0.000 D | Application root path      :  "/usr/share/PrismLauncher"
     0.000 D | <> Paths set.
     0.014 D | Detected default console font: "Liberation Mono" , substitutions: ""
     0.170 D | <> Settings loaded.
     0.186 D | Detecting proxy settings...
     0.186 D | Using no proxy is an option!
     0.186 D | <> Network done.
     0.187 C | Exception: "Unable to open /home/kruse/.local/share/PrismLauncher/translations/index_v2.json for reading: No such file or directory"
     0.187 C | Translations Download Failed: index file not readable
     0.187 W | Selected invalid language "" , defaulting to "en_US"
     0.187 D | Your language is ""
     0.187 D | <> Translations loaded.
     0.187 D | Started watching  "/home/kruse/.local/share/PrismLauncher/icons"
     0.188 D | Sorting icon list...
     0.188 D | <> Instance icons initialized.
     0.188 D | [Theme] Determining System Widget Theme...
     0.188 D | [Theme] System theme seems to be: "fusion"
     0.188 D | [Theme] <> Initializing Icon Themes
     0.188 D | [Theme] Loaded Built-In Icon Theme "pe_colored"
     0.188 D | [Theme] Loaded Built-In Icon Theme "pe_light"
     0.188 D | [Theme] Loaded Built-In Icon Theme "pe_dark"
     0.188 D | [Theme] Loaded Built-In Icon Theme "pe_blue"
     0.188 D | [Theme] Loaded Built-In Icon Theme "breeze_light"
     0.188 D | [Theme] Loaded Built-In Icon Theme "breeze_dark"
     0.188 D | [Theme] Loaded Built-In Icon Theme "OSX"
     0.189 D | [Theme] Loaded Built-In Icon Theme "iOS"
     0.189 D | [Theme] Loaded Built-In Icon Theme "flat"
     0.189 D | [Theme] Loaded Built-In Icon Theme "flat_white"
     0.189 D | [Theme] Loaded Built-In Icon Theme "multimc"
     0.189 D | [Theme] Icon Theme Folder Path:  "/home/kruse/.local/share/PrismLauncher/iconthemes"
     0.189 D | [Theme] <> Icon themes initialized.
     0.189 D | [Theme] <> Initializing Widget Themes
     0.189 D | [Theme] Loading Built-in Theme: "system"
     0.189 D | [Theme] Loading Built-in Theme: "dark"
     0.189 D | [Theme] Loading Built-in Theme: "bright"
     0.189 D | [Theme] <> Initializing System Widget Themes

(prismlauncher:6031): GLib-GObject-WARNING **: 00:33:56.586: cannot register existing type 'GdkDisplayManager'

(prismlauncher:6031): GLib-CRITICAL **: 00:33:56.586: g_once_init_leave: assertion 'result != 0' failed

(prismlauncher:6031): GLib-GObject-CRITICAL **: 00:33:56.586: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

(prismlauncher:6031): GLib-GObject-WARNING **: 00:33:56.586: invalid (NULL) pointer instance

(prismlauncher:6031): GLib-GObject-CRITICAL **: 00:33:56.586: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(prismlauncher:6031): GLib-GObject-WARNING **: 00:33:56.587: invalid (NULL) pointer instance

(prismlauncher:6031): GLib-GObject-CRITICAL **: 00:33:56.587: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Gtk-Message: 00:33:56.587: Failed to load module "canberra-gtk-module": 'gtk_module_display_init': /usr/lib/aarch64-linux-gnu/gtk-2.0/modules/libatk-bridge.so: undefined symbol: gtk_module_display_init

(prismlauncher:6031): GLib-GObject-WARNING **: 00:33:56.588: cannot register existing type 'GdkDisplay'

(prismlauncher:6031): GLib-CRITICAL **: 00:33:56.588: g_once_init_leave: assertion 'result != 0' failed

(prismlauncher:6031): GLib-GObject-CRITICAL **: 00:33:56.588: g_type_register_static: assertion 'parent_type > 0' failed

(prismlauncher:6031): GLib-CRITICAL **: 00:33:56.588: g_once_init_leave: assertion 'result != 0' failed

(prismlauncher:6031): GLib-GObject-CRITICAL **: 00:33:56.588: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
Segmentation fault
```

My `raspi-config` says I'm using the Wayland backend for graphics, but I honestly don't know much about that stuff. Any news on a fix or a workaround?

Edit: After reading the issue #4187 I tried `T_QPA_PLATFORMTHEME=gtk2 /usr/bin/prismlauncher` and suddenly it works now. IDK why.
