### ISSUE TITLE
Changing to system theme uses the light theme instead of dark theme

### ISSUE THREAD

**Issue by ghost** [PrismLauncher/PrismLauncher#490]
### Operating System

Linux

### Version of Prism Launcher

5.2 (flatpak)

### Version of Qt

Qt 5.15.6

### Description of bug

Changing to system theme uses the light theme instead of dark theme. Restarting the launcher makes it use the right theme

https://user-images.githubusercontent.com/110736028/202909002-0673b61b-5c98-4383-afaa-e9215a61e795.mp4

### Steps to reproduce

see the video

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by TayouVR** [comment]
this probably has to do with the flatpak runtime not being aware of the system theme? maybe? 
Though your desktop is not plasma, but a GTK based one as far as i can tell... do you have QGnomePlatform installed? Prism doesn't have any light/dark logic, it only applies full themes / color palettes, which would be provided by the Qt system theme.

**Comment by ghost** [comment]
> this probably has to do with the flatpak runtime not being aware of the system theme? maybe?

Yeah, the bug isn't present when I install prism from the void repos

> do you have QGnomePlatform installed?

Yes

**Comment by yavko** [comment]
I have this issue, and I'm using Nix flake, started happening recently used to use my kvantum theme, but no longer

**Comment by Scrumplex** [comment]
Can confirm the behavior described by @yavko.

This was introduced by PR #249 

I assume it initially re-setting the system theme on launch breaks the stylesheet.

This is reproducible when using a different color scheme in qt6ct.

**Comment by TayouVR** [comment]
> This was introduced by PR #249

I'm not really sure what part of that PR actually changes the behaviour there..


> I assume it initially re-setting the system theme on launch breaks the stylesheet.

The logic in Application.cpp does not set the system theme unless no theme is defined initially, that is the same as it was before the PR.

Could it have to do with the removal of the hasStyleSheet() check in ITheme::apply()?
That seems like a more likely cause of error. Though I'm sure there was some reason why I got rid of it...
Maybe it was because of the whole crashing situation? I really don't recall... 🤔

**Comment by yavko** [comment]
> Can confirm the behavior described by @yavko.
> 
> This was introduced by PR #249
> 
> I assume it initially re-setting the system theme on launch breaks the stylesheet.
> 
> This is reproducible when using a different color scheme in qt6ct.

Forgot to mention, it only happens with the QT6 version of prism, once I switched back to qt5 it went away

**Comment by Scrumplex** [comment]
Should be fixed now. I am also running the develop branch using the Nix flake and I have my dark theme now :D

**Comment by yavko** [comment]
> Should be fixed now. I am also running the develop branch using the Nix flake and I have my dark theme now :D

Good to hear!

**Comment by NoelGisler** [comment]
not to be a partypooper, but this still happens for me on NixOS and GNOME

Flatpak works, native Package doesn't

**Comment by Scrumplex** [comment]
@Neon-44 do you know if other Qt 6 apps work?

**Comment by NoelGisler** [comment]
Is the Dolphin File Manager QT6? i installed the Flatpak of that and it doesn't work either.
